{ pkgs, ... }:
{
  projectRootFile = "flake.nix";

  programs = {
    # Go formatting.
    gofumpt = {
      enable = true;
      extra = true; # enable extra rules beyond `gofmt -s`
    };
    goimports.enable = true;

    # Nix formatting.
    nixfmt.enable = true;

    # YAML / JSON / TOML formatting.
    yamlfmt.enable = true;
    taplo.enable = true;
    # mdformat is intentionally disabled: it mangles YAML frontmatter (treating
    # `---` as horizontal rules) and renumbers ordered lists, which breaks
    # `.github/ISSUE_TEMPLATE/*.md` and rewrites the planning docs. Markdown
    # in this repo stays human-formatted.
  };

  settings = {
    global.excludes = [
      "/bin/*"
      "/ingest"
      "/worker"
      "/resolver"
      "/result"
      "/result-*"
      "*.log"
      ".direnv/*"
      "/secrets/*"
      "deploy/scripts/skiff-keys.env"
      "**/skiff-keys.env"
      "*.signing-key"
      "*.signing-key.pub"
      "flake.lock"

      # Fixture tarballs are binary; they are deterministically regenerated by
      # pkg/classify/testdata/build-fixtures.sh.
      "pkg/classify/testdata/**/*.tgz"
      "pkg/classify/testdata/**/*.tar"

      # Generated migration SQL — formatter would mangle indentation conventions.
      "pkg/store/migrations/*.sql"

      # The contributor covenant text in CODE_OF_CONDUCT.md follows upstream verbatim.
      "CODE_OF_CONDUCT.md"
    ];

  };
}
